name: Benchmark Comparison

on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # important to fetch full history for git compare

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"


      - uses: astral-sh/setup-uv@v7

      - name: Install base
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}
          uv pip install --system '.[test]'

      # Run benchmarks on base
      - name: Run benchmarks on base
        run: |
          pytest benchmarks --benchmark-only --benchmark-save=base --no-cov --disable-warnings
          # Move benchmark results to safe location
          mkdir -p /tmp/benchmarks
          cp -r .benchmarks/* /tmp/benchmarks/


      - name: Install PR
        run: |
          git checkout -
          uv pip install --system '.[test]'
          # Restore benchmark results
          mkdir -p .benchmarks
          cp -r /tmp/benchmarks/* .benchmarks/

      # Run benchmarks on MR
      - name: Run benchmarks on MR
        run: |
          pytest benchmarks --benchmark-only --benchmark-save=mr --benchmark-compare=base --benchmark-compare-fail=min:10% --no-cov --disable-warnings

      # Compare results
      - name: Run benchmarks on PR and compare
        id: compare
        run: |
          set +e
          result=$(pytest-benchmark compare)
          echo "$result"
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Post a comment to the PR with results
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: benchmark
          message: |
            ## 🏎️ Benchmark Comparison
            ```
            ${{ steps.compare.outputs.result }}
            ```
